version: '3.7'

services:
    db:
        image: mysql
        command: ["--default-authentication-plugin=mysql_native_password"]
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: symfony
            MYSQL_USER: symfony
            MYSQL_PASSWORD: symfony

    php:
        build: ./docker/php
        ports:
            - "9000:9000"
        volumes:
            - ./project:/var/www/app
            - ./docker/logs/symfony:/var/www/app/var/log
        links:
            - db
        extra_hosts:
            - "car.localhost:10.3.4.77"

    nginx:
        build: ./docker/nginx
        ports:
            - "8080:80"
        links:
            - php
        volumes:
            - ./project:/var/www/app
            - ./docker/logs/nginx:/var/log/nginx
    mysql:
        image: mysql
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: test
            MYSQL_USER: test
            MYSQL_PASSWORD: test
            MYSQL_DATABASE: test

    redis:
        image: redis
